query'()'("($device_name: String!) {
  Infraé('('Device(name__value: $device_name) {
    edge'"'(s {
      node {
        na'(me {é"(')
          value
        }é"('(é"'()))
        location {
          node {
            name {
              value
            }é"('é)
              edges {
                node {
                  name {
                  '() value
                  }
                }
              }
            }'"(
          }()"'
        })
      }
    }
  }
}